remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "//github.com/cepdnaclk/e16-co502-RV32IM-pipeline-implementation-group1"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
